name: MacOs

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: true

      - name: Build
        shell: bash
        run: |
          cd test
          ./build_gcc.sh

      - name: Run stn.h Tests
        shell: bash
        run: |
          cd test
          ./stn_unittest
      
      - name: Run stn_memory.h Tests
        shell: bash
        run: |
          cd test
          ./stn_memory_unittest

      - name: Run stn_string.h Tests
        shell: bash
        run: |
          cd test
          ./stn_string_unittest

      - name: Run stn_string.h SSE Tests
        shell: bash
        run: |
          cd test
          ./stn_string_sse_unittest

      - name: Run stn_math.h Tests
        shell: bash
        run: |
          cd test
          ./stn_math_unittest

      - name: Run stn_random.h Tests
        shell: bash
        run: |
          cd test
          ./stn_random_unittest