name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: true
      
      - name: Setup cl.exe
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: cmd
        run: |
          cd test
          build_msvc.bat

      - name: Run stn.h Tests
        shell: cmd
        run: |
          cd test
          stn_unittest.exe
      
      - name: Run stn_memory.h Tests
        shell: cmd
        run: |
          cd test
          stn_memory_unittest.exe